- name: setup autelia+lldap+postgres+caddy
  hosts: auth
  any_errors_fatal: true
  vars_files:
  - ../../inventory/group_vars/authentication/vault.yml
  roles:
  #- docker
  #- authDB
  - lldap
  #- authelia
  #- caddy
